services:
  - type: web
    name: useful-tools
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_NAME
        value: "便利ツール集"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: APP_LOCALE
        value: ja
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: LOG_LEVEL
        value: error
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: MAIL_MAILER
        value: log
    
databases:
  - name: useful-tools-db
    databaseName: useful_tools
    user: useful_tools_user
    plan: free